version: '3.7'

services:

  django:
    container_name: support
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "python /usr/src/djangoInnowise/manage.py migrate --noinput &&
             python /usr/src/djangoInnowise/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/djangoInnowise
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - support_db

  support_db:
    image: postgres:12
    restart: always
    volumes:
       - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: simple_db

  redis:
    image: redis
  celery:
    image: celery
    build:
      context: ./
      dockerfile: Dockerfile
    command: celery -A djangoInnowise worker -l info
    restart: always
    env_file:
      - ./.env.dev
    volumes:
     - .:/usr/src/djangoInnowise
    depends_on:
        - redis
        - support_db
        - django

  celery_beat:
    build:
      context: ./
      dockerfile: Dockerfile
    command: celery -A djangoInnowise beat -l info
    volumes:
      - .:/usr/src/djangoInnowise
    env_file:
      - ./.env.dev
    depends_on:
      - django
      - redis

  flower:
    image: flower
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    command: celery -A djangoInnowise flower --adress=192.168.99.100 --port=5566
    env_file:
      - ./.env.dev
    depends_on:
      - django
      - celery
      - redis

volumes:
  pg_data:
