version: '3.7'

services:

  django:
    container_name: support
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/djangoInnowise
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - support_db

  support_db:
    image: postgres:12
    restart: always
    volumes:
       - pg_data:/var/lib/postgresql/data
    env_file:
      - ./.env.dev.db


  redis:
    image: redis
  celery:
    image: celery
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env.dev
    volumes:
     - .:/usr/src/djangoInnowise
    depends_on:
        - redis
        - support_db
        - django

  celery_beat:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/djangoInnowise
    env_file:
      - ./.env.dev
    depends_on:
      - django
      - redis

  flower:
    image: flower
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env.dev
    depends_on:
      - django
      - celery
      - redis

volumes:
  pg_data:
